[project]
name = "srs-sql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "duckdb>=1.4.4",
    "pandas>=2.3.3",
    "streamlit>=1.53.1",
]
